driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  <% %w[5.5 5.6].each do |version| %>
  - name: client_<%= version.tr(".", "") %>
    attributes:
      percona:
        apt_keyserver: hkp://pgp.mit.edu:80
        version: "<%= version %>"
    run_list:
      - recipe[percona::client]
      - recipe[percona::toolkit]

  - name: server_<%= version.tr(".", "") %>
    run_list:
      - recipe[percona::server]
    attributes:
      percona:
        apt_keyserver: hkp://pgp.mit.edu:80
        version: "<%= version %>"
        server:
          jemalloc: true
          debian_password: d3b1an
          root_password: r00t
  <% end %>

  - name: xtrabackup
    run_list:
      - recipe[percona::server]
      - recipe[percona::backup]

  - name: new_datadir
    run_list:
      - recipe[percona::server]
    attributes:
      percona:
        server:
          datadir: "/tmp/mysql"
